import img1 from "@/assets/img-1.webp"
import img2 from "@/assets/img-2.webp"
import img3 from "@/assets/img-3.webp"
import img4 from "@/assets/img-4.webp"
import img5 from "@/assets/img-5.webp"
import img6 from "@/assets/img-6.webp"
import img7 from "@/assets/img-7.webp"
import img8 from "@/assets/img-8.webp"
import img9 from "@/assets/img-9.webp"
import img10 from "@/assets/img-10.webp"
import img11 from "@/assets/img-11.webp"
import img12 from "@/assets/img-12.webp"
import img13 from "@/assets/img-13.webp"

export const galleryImages = [img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13]
