name: ci

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm build

  deploy-to-development:
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    needs: build
    environment: development
    steps:
      - run: echo "Deploying to development"

  deploy-to-production:
    if: github.event.pull_request.merged == true && github.base_ref == 'main' && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - run: echo "Deploying to production"
